name: Android rom application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
        path: tools
        repository: wuxianlin/android_rom_tools

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt-get install axel brotli maven
        ./tools/setup.sh ${{ secrets.GITHUB_TOKEN }}
        python -m pip install --upgrade pip
        if [ -f tools/requirements.txt ]; then pip install -r tools/requirements.txt; fi
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run
      run: |
        bash jadx.sh

    - name: Commit and push changes
      run: |
        git config user.email "noreply@github.com"
        git config user.name "GitHub Action"
        git add rom-decompiled-jadx
        if [ -z "$(git status --porcelain)" ]; then
          echo "No changes to commit"
        else
          git commit -m "auto update"
          git push
        fi


